name: Pull Request

on:

  pull_request:
    branches:
      - main

jobs:

  docker_build:
    uses: "philipcristiano/workflows/.github/workflows/docker-build.yml@multi-platform-docker"
    with:
      platforms: amd64,arm64


  erlang:
    uses: "philipcristiano/workflows/.github/workflows/rebar3.yml@main"
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  js:
    uses: "./.github/workflows/r-javascript.yml"
    with:
      context: ./ui
