name: Pull Request

on:

  pull_request:
    branches:
      - main

jobs:

  check-for-cc:
    runs-on: ubuntu-latest
    steps:
      - name: check-for-cc
        id: check-for-cc
        uses: agenthunt/conventional-commit-checker-action@v2.0.0

  docker_build:
    uses: "philipcristiano/workflows/.github/workflows/docker-build.yml@main"
    with:
      timeout: 25

  rust:
    uses: "philipcristiano/workflows/.github/workflows/rust.yml@main"
    with:
      setup_script: |
          curl -sL https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.1/tailwindcss-linux-x64 -o tailwindcss
          chmod +x tailwindcss
          mv tailwindcss /usr/local/bin

  flake:
    uses: "philipcristiano/workflows/.github/workflows/nix.yml@main"
    with:
      flakes-from-devshell: true
      script: |
        unset DATABASE_URL
        export SQLX_OFFLINE=true
        cargo build

  database:
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: folio
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4.1.3

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Enable extension
        env:
          PGPASSWORD: postgres
        run: psql -h 127.0.0.1 -d folio -U postgres -tc "CREATE EXTENSION pgcrypto;"

      - uses: workflow/nix-shell-action@v3.3.0
        with:
          flakes-from-devshell: true
          script: |
            unset DATABASE_URL
            cargo build --bin folio-migrate
            cargo run --bin folio-migrate -- --config-file="config.github-actions.toml" migrate
