name: Pull Request

on:

  pull_request:
    branches:
      - main

jobs:

  docker_build:
    uses: "philipcristiano/workflows/.github/workflows/docker-build.yml@main"
    with:
      qemu_platforms: amd64,arm64
      docker_platforms: linux/amd64,linux/arm64/v8
      timeout: 25

  erlang:
    uses: "philipcristiano/workflows/.github/workflows/rebar3.yml@main"
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  js:
    uses: "./.github/workflows/r-javascript.yml"
    with:
      context: ./ui
